### ISSUE TITLE
La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#1]
Primero, que la entendiste al revés: `Martes` viene después que `Lunes`, pero vos devolvés justo lo contrario.

Por otra parte, `Miercoles` viene después que `Lunes`, pero tu función (suponiendo que la invertimos), no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by TomasCenturion** [comment]
Fidel, ya corregí los detalles y errores que me señalaste arreglar. Saludos!
