### ISSUE TITLE
Pr3: falta atreverse al desafío... :-D

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#18]
Es interesante de pensar. Consejo: dividir en subtareas... ;)

**Comment by TomasCenturion** [comment]
Corregido.

**Comment by fidel-ml** [comment]
El nombre `cantTesorosEnCamino` es confuso, porque no mira todo el camino, sino HASTA la posición dada...

**Comment by TomasCenturion** [comment]
Corregido.

**Comment by fidel-ml** [comment]
Pero `cantTesorosEnPosición` me indicaría que cuenta en una ÚNICA posición. Y vos estás contando en más lugares, o sea HASTA la posición que es argumento. Tenés que ser preciso con los nombres...

**Comment by TomasCenturion** [comment]
El nombre ya está corregido. Gracias por la obsevación, Fidel!
