### ISSUE TITLE
Pr3: `todosLosCaminos` no es correcta

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#24]
No estás dando TODOS los caminos, sino solamente los maximales. La idea es que la cantidad de caminos del resultado sea igual a la cantidad de elementos...

**Comment by TomasCenturion** [comment]
Corregido.

**Comment by fidel-ml** [comment]
Ahora tiene un caso innecesario.
Además, el nombre de la auxiliar `prepend` es confuso, porque no hace `prepend` sobre el argumento (como da a entender el nombre), sino sobre cada uno de sus elementos...

**Comment by TomasCenturion** [comment]
Corregido.
