### ISSUE TITLE
Pr2: en `zipMaximos` el primer caso es innecesario

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#5]
NUNCA hagas doble PM a menos que sea imprescindible para resolver el problema. En este caso, la primera ecuación queda resuelta por la segunda, y entonces es innecesario tenerla...

**Comment by TomasCenturion** [comment]
Corregido

**Comment by fidel-ml** [comment]
Ahora estás dando un resultado incorrecto, porque perdés elementos...

**Comment by TomasCenturion** [comment]
Corregido
