### ISSUE TITLE
Pr2: en `losPrimeros` faltan casos

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#6]
NUNCA hagas doble PM a menos que sea necesario... Siempre empezá pensando UNA recursión, y si hace falta, DESPUÉS otra. No ambas al mismo tiempo.

**Comment by TomasCenturion** [comment]
Corregido

**Comment by fidel-ml** [comment]
No lo veo corregido. Está exactamente igual que antes...

**Comment by TomasCenturion** [comment]
Corregido
