### ISSUE TITLE
Pr 2: En la función `esMaestroPokemon` usás la cantidad para mirar existencia

### ISSUE THREAD

**Issue by fidel-ml** [TomasCenturion/EstrD22s1#9]
En Introducción vieron que cuando se hace una búsqueda no es feliz reemplazarla por una totalización y pregunta posterior.
Suponete que hay 1 millón de elementos, y el que buscás está primero. En una búsqueda mirás solamente el primero y decís "está". En una totalización tenés que recorrer TODO el millón para sumar 1, y recién ahí comparar con 0. Es MUCHO más trabajo, y conceptualmente incorrecto.

**Comment by TomasCenturion** [comment]
Corregido

**Comment by fidel-ml** [comment]
Ahora tenés el primer caso innecesario, porque está contemplado en el 2do... Esto lo vimos ayer en clase...

**Comment by TomasCenturion** [comment]
Corregido
